name: Reset cache

on:
  push:
    branches:
      - main

jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: Reset cache
      run: |
        curl -X GET "https://v3.avohq.io/templates/reset?secret=${{secrets.GH_API_SECRET}}&repo=$GITHUB_REPOSITORY"